version: "3.8"
services:
  app:
    container_name: github-sync-with-notion
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PERSONAL_GITHUB_ACCESS_KEY
      - NOTION_API_KEY
      - NOTION_ISSUE_DATABASE_ID
      - REPO_OWNER
      - REPO_NAME
