name: Feature
description: Submit a proposal for a new feature
title: "[Feature]: "
labels: ["Feature 🧐"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation 🧐"
      description: 왜 이 기능을 만들어야 하는지 설명해주세요.
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: "TO DO 📑"
      description: 이 기능을 만들기 위해 해야 할 일들을 적어주세요.
    validations:
      required: true
