on:
  issues:
    types: [opened, reopened, closed, deleted]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PERSONAL_GITHUB_ACCESS_KEY: ${{ secrets.PERSONAL_GITHUB_ACCESS_KEY }}
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      NOTION_ISSUE_DATABASE_ID: ${{ secrets.NOTION_ISSUE_DATABASE_ID }}
      REPO_OWNER: ${{ secrets.REPO_OWNER }}
      REPO_NAME: ${{ secrets.REPO_NAME }}

    name: "Run github issue sync with notion"
    steps:
      - uses: actions/checkout@v2
      - name: create env file
        run: |
          touch .env
          echo PERSONAL_GITHUB_ACCESS_KEY=${{ env.PERSONAL_GITHUB_ACCESS_KEY }} >> .env
          echo NOTION_API_KEY=${{ env.NOTION_API_KEY }} >> .env
          echo NOTION_ISSUE_DATABASE_ID=${{ env.NOTION_ISSUE_DATABASE_ID }} >> .env
          echo REPO_OWNER=${{ env.REPO_OWNER }} >> .env
          echo REPO_NAME=${{ env.REPO_NAME }} >> .env
      - name: docker compose up
        run: docker-compose --env-file .env up
